alias mysql@5.7-start='mysql@8.0-stop || true && ( "$(brew --prefix)/opt/mysql@5.7/bin/mysqld_safe" --datadir="$(brew --prefix)/var/mysql@5.7" > /dev/null 2>&1 & )'
alias mysql@5.7-stop='"$(brew --prefix)/opt/mysql@5.7/bin/mysqladmin" -u root shutdown > /dev/null 2>&1'

alias mysql@8.0-start='mysql@5.7-stop || true && ( "$(brew --prefix)/opt/mysql@8.0/bin/mysqld_safe" --datadir="$(brew --prefix)/var/mysql@8.0" > /dev/null 2>&1 & )'
alias mysql@8.0-stop='"$(brew --prefix)/opt/mysql@8.0/bin/mysqladmin" -u root shutdown > /dev/null 2>&1'
