export GIT_EDITOR='edit --new-window --wait'

# For the settings below, read the docs for `git-prompt.sh`

# unstaged (*) and staged (+) changes will be shown next to the branch name
export GIT_PS1_SHOWDIRTYSTATE=true
# if something is stashed, then a '$' will be shown next to the branch name
export GIT_PS1_SHOWSTASHSTATE=true
# if there're untracked files, then a '%' will be shown next to the branch name
export GIT_PS1_SHOWUNTRACKEDFILES=true
# see the difference between HEAD and its upstream:
#   - "<" indicates you are behind
#   - ">" indicates you are ahead
#   - "<>" indicates you have diverged
#   - "=" indicates that there is no difference
export GIT_PS1_SHOWUPSTREAM=auto

# TODO: remove hard-coded path
export PATH="$PATH:$HOME/Development/dotfiles/software/git/bin"

# `alias` takes precedence over functions, built-ins, and $PATH
alias git=git-wrapper

# What's the "original" `git` command?
#export GIT="command git"
export GIT="hub"

# For typos:
alias gti=git
