#!/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby
require_relative '../../src/helpers'

cask 'atom-beta'

link_to_home_relative 'config.cson', '.atom/config.cson'
link_to_home_relative 'init.coffee', '.atom/init.coffee'
link_to_home_relative 'keymap.cson', '.atom/keymap.cson'
link_to_home_relative 'snippets.cson', '.atom/snippets.cson'
link_to_home_relative 'styles.less', '.atom/styles.less'

bash_source_relative

module APM
  def self.install(package_name)
    return if Kernel.system(
      "apm-beta list --bare --installed "\
      "| cut -f 1 -d@ -s "\
      "| grep ^#{package_name}$ "\
      "> /dev/null"
    )
    Kernel.system "apm-beta install #{package_name}"
  end
end

ATOM_PACKAGES_FILE="#{__dir__}/packages.autogenerated"

File.readlines(ATOM_PACKAGES_FILE).each do |package|
  APM.install package.chomp
end

ATOM_PACKAGES_PATH="#{ENV["HOME"]}/.atom/packages"

Kernel.system(
  "find #{ATOM_PACKAGES_PATH} "\
  "  -maxdepth 1 "\
  "  -type d "\
  "  ! -path #{ATOM_PACKAGES_PATH} "\
  "  -exec basename {} \\; "\
  "| sort "\
  "> #{ATOM_PACKAGES_FILE}"
)
