# # `DOCKER_HOST` value below comes from `docker context ls`
# #
# # See below for more:
# #   * https://github.com/aws/aws-sam-cli/issues/4329#issuecomment-1289588827
# #   * https://stackoverflow.com/a/75216249/11895
# #
# alias sam='DOCKER_HOST="unix://$HOME/.docker/run/docker.sock" sam'
