envchain() {
    if [ "$#" -ne 2 ] || [ "$1" != "--list" ]; then
        command envchain "$@"
        return
    fi

    local namespace
    namespace="$2"

    local env_vars
    env_vars=$(command envchain "--list" "$namespace")

    command envchain "$namespace" sh -c "printenv | grep --extended-regexp '^(${env_vars//$'\n'/|})='"
}
